<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\Services\" />
    <Folder Include="Application\Commands\" />
    <Folder Include="Application\Dtos\" />
    <Folder Include="Application\Validation\" />
    <Folder Include="Common\" />
    <Folder Include="Domain\" />
  </ItemGroup>

</Project>
