<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PersonalBusinessManager.Core\PersonalBusinessManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PersonalFinanceReports\" />
    <Folder Include="Formatting\" />
    <Folder Include="Templates\" />
    <Folder Include="BusinessReports\" />
    <Folder Include="Invoices\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
