<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PersonalBusinessManager.Core\PersonalBusinessManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentMigrator.Runner.Core" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner.MySql" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\Sql\" />
    <Folder Include="Database\Transactions\" />
    <Folder Include="Database\Repositories\" />
    <Folder Include="Backups\" />
    <Folder Include="Logging\" />
    <Folder Include="Settings\" />
    <Folder Include="Clock\" />
    <Folder Include="Files\" />
    <Folder Include="Security\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
